/** @type {import('next').NextConfig} */
const nextConfig = {
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'avatars.githubusercontent.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'cdn.discordapp.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'res.cloudinary.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'plus.unsplash.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'cdn.sanity.io',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'source.unsplash.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'github.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'raw.githubusercontent.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'img.clerk.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'utfs.io',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'files.stripe.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'uploadthing.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'placehold.co',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'placehold.it',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'place-hold.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'via.placeholder.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'dummyimage.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.fillmurray.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placecage.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.stevensegall.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placebear.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placeskull.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placekitten.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placedog.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.fillmurray.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placecage.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.stevensegall.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placebear.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placeskull.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placekitten.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.placedog.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'www.loremflickr.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'unsplash.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'source.unsplash.com',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'v0.dev',
        port: '',
        pathname: '**',
      },
      {
        protocol: 'https',
        hostname: 'blob.v0.dev',
        port: '',
        pathname: '**',
      },
    ],
    unoptimized: true,
  },
};

export default nextConfig;
